# Generated by Django 4.2.7 on 2023-11-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/', verbose_name='PDFS')),
            ],
        ),
        migrations.DeleteModel(
            name='PDF',
        ),
    ]
