<<<<<<< HEAD:american_ai_tutor/ai_tutor/migrations/0002_bannend_word.py
# Generated by Django 4.2.8 on 2024-01-09 12:18
=======
# Generated by Django 4.2.9 on 2024-01-09 06:03
>>>>>>> a48600a702112eeaeac2b6ff98770c5ea6e3fec8:ahsa/ai_tutor/migrations/0002_bannend_word.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannend_word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
