<<<<<<< HEAD:american_ai_tutor/ai_tutor/migrations/0003_feedback.py
# Generated by Django 4.2.9 on 2024-01-24 07:25
=======
# Generated by Django 4.2.9 on 2024-01-24 06:01
>>>>>>> a48600a702112eeaeac2b6ff98770c5ea6e3fec8:ahsa/ai_tutor/migrations/0003_feedback.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_tutor', '0002_bannend_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD:american_ai_tutor/ai_tutor/migrations/0003_feedback.py
                ('question', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('is_positive', models.BooleanField(blank=True, null=True)),
=======
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('is_positive', models.BooleanField()),
>>>>>>> a48600a702112eeaeac2b6ff98770c5ea6e3fec8:ahsa/ai_tutor/migrations/0003_feedback.py
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
