# Generated by Django 4.2.9 on 2024-01-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0004_alter_feedback_is_positive_alter_feedback_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_positive',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
